#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "lazylibrarian"
name = "LazyLibrarian"
description.en = "Follow authors and grab metadata for all your digital reading needs"
description.fr = "Suivez vos auteurs préférés et récupérez les métadonnées pour tous vos besoins en matière de lecture numérique"

version = "2026.04.20~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "AGPL-3.0-only"
admindoc = "https://lazylibrarian.gitlab.io/"
code = "https://gitlab.com/LazyLibrarian/LazyLibrarian"

[integration]
yunohost = ">= 12.1.39"
helpers_version = "2.1"
architectures = "all"
multi_instance = false

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://gitlab.com/LazyLibrarian/LazyLibrarian/-/archive/652b2d0d30a68e3034339554c6f6113cf0581521/LazyLibrarian-652b2d0d30a68e3034339554c6f6113cf0581521.tar.bz2"
    sha256 = "9f45d12939f64504aeb8c73c2d11a238975a7bb50092bbcbc5ab5fa5a9c3be87"

    autoupdate.strategy = "latest_gitlab_commit"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 5299

    [resources.apt]
    packages = "python3-dev, python3-venv, python3, python3-pip, libcurl4-openssl-dev, libssl-dev"
